// 平台无关入口：浏览器/edge 可用。禁止从此文件 import 任何 Node-only 模块。
export { runAgent } from './run-agent.js';
export type { RunAgentParams, RunAgentResult } from './run-agent.js';
export { AgentState } from './agent-state.js';
export { assembleAgentContext, buildRuleSecurity } from './agent-context-assembler.js';
export type { AssembleAgentContextOptions } from './agent-context-assembler.js';
export type { AgentContext, AgentRuntimeInfo } from './agent-context.js';
export { createCoreModels } from './llm/models.js';
export type { CreateCoreModelsOptions } from './llm/models.js';
export { generateId } from './shared/generate-id.js';
export { log, setLogSink, configureConsoleOutput, flushDebugLog, isDebugEnabled } from './shared/debug-log.js';
export { StaticToolProvider } from './plugins/tool/static/index.js';
export type { CustomTool } from './plugins/tool/static/index.js';
export { EmptySkillProvider } from './plugins/skill/empty/index.js';
export { SimpleContextProvider } from './plugins/memory/simple/index.js';
export { ReactLoop } from './plugins/loop/react/index.js';
export { UnsupportedSessionSchemaError } from './plugins/session/errors.js';
// system-prompt 纯件：从具体模块文件导入，避开含 fs 的 loaders/project-agents-md-loader。
export { DefaultSystemPromptAssembler } from './system-prompt/assembler.js';
export { ProviderAwareTemplateSelector } from './system-prompt/template-selector.js';
export { ClaudeAgentPromptTemplate } from './system-prompt/templates/claude-template.js';
export { OpenAiAgentPromptTemplate } from './system-prompt/templates/openai-template.js';
export { ToolingSection } from './system-prompt/sections/tooling-section.js';
export { ExecutionBiasSection } from './system-prompt/sections/execution-bias-section.js';
export { SafetySection } from './system-prompt/sections/safety-section.js';
export { WorkspaceSection } from './system-prompt/sections/workspace-section.js';
export { AgentsMdSection } from './system-prompt/sections/agents-md-section.js';
export { SkillsSection } from './system-prompt/sections/skills-section.js';
export { RuntimeSection } from './system-prompt/sections/runtime-section.js';
// sdk 类型
export type * from './sdk/config-provider.js';
export type * from './sdk/session-provider.js';
export type * from './sdk/tool-provider.js';
export type * from './sdk/skill-provider.js';
export type * from './sdk/storage-provider.js';
export type * from './sdk/system-prompt.js';
export type * from './sdk/compressor.js';
export type * from './sdk/title-provider.js';
export type * from './sdk/loop-strategy.js';
export type * from './sdk/context-provider.js';
export type * from './sdk/budget-policy.js';
export type * from './sdk/error-handler.js';
export type * from './sdk/tool-composer.js';
export type * from './sdk/agent-role.js';
export type * from './sdk/agent-state-provider.js';
export type { Session, SessionSummary } from './session.js';
export type { Rule, RuleSource } from './security/rules/rule.js';
export type { TodoItem } from './todo/types.js';
export type { SecurityMode } from './security/permissions/factory.js';
export type { UserInput, UserInputContent, AgentOutput, AgentStream, AgentStreamEvent } from './types.js';
export type { McpServerConfig } from './mcp/types.js';
export type { Message, TextContent, ThinkingContent, ToolCall, Models, Usage } from '@earendil-works/pi-ai';
export type { Provider } from '@earendil-works/pi-ai';
export type { RemMessage } from './types.js';
