// ═══ 稳定 API：Agent 工厂、Agent/Session 核心类型、SDK 接口、装配入口 ═══
export * from './agent/types.js'
export type { Message, TextContent, ImageContent, ThinkingContent, ToolCall, Usage, AssistantMessage, AssistantMessageEvent } from '@earendil-works/pi-ai'
export type { AgentEvent } from '@earendil-works/pi-agent-core'
export * from './session/model.js'
export * from './sdk/index.js'
export * from './plugins/index.js'
export { createAgentFromEnv, type CreateAgentOptions } from './assembly/agent-factory.js'
export { createAgentAssembly, type AgentContextBuildOptions } from './assembly/agent-assembly.js'
export type { AgentDI } from './assembly/agent-di.js'
export type { AgentRuntimeConfig, AgentRuntimeInfo } from './assembly/runtime-config.js'
export type { AgentAssembly } from './assembly/types.js'
export { initRuleEngine, initializeAgentDI } from './assembly/agent-context-assembler.js'
export { REMAgent, type REMAgentStatus, type REMAgentParams, type ApprovalStateLike } from './agent/rem-agent.js'
export type { REMAgentEvent } from './agent/agent-event.js'
export { resolveREMAgentContext } from './agent/context/resolve.js'
export type { REMAgentContext, ResolveREMAgentContextParams } from './agent/context/types.js'
export * from './agent/bus-events.js'
export * from './agent/broadcast-bus.js'
export * from './agent/budget.js'
export * from './agent/token-usage.js'
export * from './agent/event-aggregators.js'
export * from './session/manager/index.js'
export * from './capabilities/todo/types.js'
export * from './capabilities/todo/errors.js'
export * from './capabilities/todo/service.js'
export * from './infrastructure/config/paths.js'
export * from './infrastructure/observability/debug-log.js'
export { createCoreModels, type CreateCoreModelsOptions } from './infrastructure/llm/models.js'
export * from './infrastructure/llm/context-window.js'
export { generateId } from './shared/generate-id.js'

// ═══ 高级 API：工具编排、安全规则、运行时桥接 ═══
export * from './tools/registry.js'
export { composeToolProviders } from './tools/composer.js'
export { ToolOverlay, defineOverlayTool, type ToolOverlayEntry } from './tools/overlay.js'
export type { Rule, RuleAction, RuleSource } from './security/rules/rule.js'
export type { ToolProfileId } from './security/rules/profiles.js'
export { RuleEngine } from './security/rules/rule-engine.js'
export { RuleStore } from './security/rules/rule-store.js'
export { getProfileRules } from './security/rules/profiles.js'
export { classifyCommand } from './security/permissions/exec-classifier.js'
export { ApprovalEngine, type ApprovalResolution } from './security/approval/approval-engine.js'
export { createToolBridge, type ToolBridgeParams, type ToolBridge } from './runtime/tool-bridge.js'
export { createContextBridge, type ContextBridgeParams, type ContextBridge } from './runtime/context-bridge.js'
export { createPiAgent, type PiAgentFactoryParams } from './runtime/pi-agent-factory.js'
export type { PiAgentLike } from './runtime/pi-agent-like.js'
export { EventQueue } from './agent/event-queue.js'
export { createTodoWriteToolDefinition, createTodoWriteToolExecutor } from './plugins/tool/builtin/todo-write.js'
export { buildChildContext, type BuildChildContextOptions } from './capabilities/sub-agent/build-child-context.js'
export { formatTaskResult } from './capabilities/sub-agent/format-task-result.js'
export { createDelegateTaskExecutor, createDelegateTaskToolDefinition, type DelegateTaskExecutorParams, type DelegateTaskInput, type SpawnChild } from './capabilities/sub-agent/delegate-task.js'
export type { PromptBuildContext } from './sdk/system-prompt.js'

// ═══ 临时兼容 API：见 compat.ts 的删除条件 ═══
export * from './compat.js'
